const devFlutterApside = "      Je travaille au sein du Lab Apside Lyon sur un projet de co-piétonnage en Flutter. Cette application va permettre aux utilisateurs de partager - avec d'autres personnes - des portions de trajets communes. L'application va proposer un service de statistiques aux entreprises et aux municipalités sur les zones de fortes fréquentations, des heures de pointes, des zones \"blanches\" ainsi que des lignes à privilégier.";
const devCsharpApside = "      Durant cette mission j’ai assuré la maintenance d'une trentaine d'applications au sein d'une TMA (Tierce Maintenance Applicative) pour L'Oréal. J’ai travaillé sur différentes technologies Microsoft : C#, .NET Framework / .NET Core : ASP.NET / SQL Server + SSMS / Visual Basics.";

const septAjdApside = "Septembre 2021 - Aujourd'hui";

const lyonApside = "Lyon, Auvergne-Rhône-Alpes, France";
const clermontVille = "Clermont-Ferrand, Auvergne-Rhône-Alpes, France";
const brestVille = "Brest, Bretagne, France";
const sbVille = "Saint-Brieuc, Bretagne, France";

const prepaCommandes = "      Emploi saisonnier dans lequel j'avais comme tâches: \n -Vider des containers de meubles et de cartons pesants plusieurs kilogrammes. \n -A l'aide d'un transpalette, récupérer les meubles commandés par les différents magasins en France, les poser sur des palettes et filmer ces dernières";
const stageCGI = "      Développement d'un outil de migration de données (MongoDB/Neo4J/ReactiveX/VertX) Dans un contexte compliqué, c\'est confiné que j’ai relevé les défis et les problématiques qui se sont présenté à moi. Plus une opportunité qu\'une contrainte, le confinement m’a permis de diversifier mes expériences professionnelles et d’accroître mon autonomie, mon organisation et ma capacité de communication.";
const reserve = "      Durant cette mission dans la réserve opérationnelle Marine, j'étais réguliérement mobilisé à l'Arsenal de Brest pour effectuer différentes missions : Service général, surveillance de site... J'ai pu y accroître certaines de mes compétences comme la rigueur et l'autonomie par le biais de tâches intellectuelles ou physiques. Mon serieux et mon assiduité ont été récompensés par une notation annuelle élogieuse ainsi qu'une montée en grade (Matelot de Première Classe [MO1]) ";

const mastere1 = "      Le Mastère Expert en Développement Logiciel, Mobile & IoT est un parcours dans lequel je suis formé au développement logiciel avancé, le développement mobile et au testing (unitaires, intégrations, fonctionnels...).\n\nLa particularité d'Ynov Lyon Campus c'est que nous avons un module nommé \"YDays\", ce module consiste à développer un projet avec plusieurs personnes appartenant à d'autres formations, par exemple Mastère Marketing et Communication, Design, Animation 3D, Cloud etc... \n\nLe projet sur lequel je travaille est une application mobile de paris e-Sportif, les technologies choisies sont le Flutter et Firebase.";
const mastere2 = "      Le Mastère Expert en Développement Logiciel, Mobile & IoT mène à un Titre RNCP de Niveau 7, ce qui est l'équivalent d'un Bac +5. \nLe Titre RNCP a pour objectif de permettre aux apprenants de disposer des compétences suivantes: \n\n1. Analyser et définir la stratégie du système d’information. \n\n2. Maintenir le système d’information en condition opérationnelle. \n\n3. Gérer un projet informatique";
const lp = "      Cette formation m'a permis d'acquérir de nombreuses compétences dans le domaine du développement mobile et logiciel. \n\nJ'ai eu l'opportunité de développer des applications - dans le cadre de projets scolaires - en différents langages : Java, Kotlin, Swift, Angular... Je me suis également investi dans la vie étudiante puisque j'ai été élu délégué de classe.";
const dut = "      Ce Diplôme Universitaire Technologique m'a permis de développer mes compétences en programmation, notamment en Algorithmie avec le C et en Programmation Orientée Objet avec du Java, puis en C#. \n\nDurant ces deux années j'ai été délégué de classe et membre du Club Info. \n\nLe Club Info est une association qui se déroule tous les Jeudis à partir de 13h, on y développe des projets avec des associations, des écoles ou des projets personnels. \n\nParticiper au club m'a permis de grandement m'améliorer en développement.";
const bac = "      Le Bac STI2D a été pour moi l'année où j'ai été initié la programmation et cela m'a donné envie de poursuivre mes études dans cette voie. Depuis la classe de Seconde je me suis investi dans la vie du lycée";
const reserveFormation = "      Dans le cadre de cette Préparation Militaire Marine nous avons appris les différents rudiments de la vie de militaire, la marche au pas, participer à des cérémonies... nous avons été embarqué à bord de plusieurs bâtiments et mis en condition de combat lors d'une séance de tir au FAMAS. ✅ Cette formation a renforcée certaines qualités comme l'esprit d'équipe, l'organisation, la minutie et la ponctualité. Je serai donc un atout fiable et actif dans votre organisation.";